import Head from 'next/head';
import 'tailwindcss/tailwind.css';


import Navbar from './components/Navbar/index';
import Banner from './components/Banner/index';
import Aboutus from './components/Aboutus/index';
import Dedicated from './components/Dedicated/index';
import Digital from './components/Digital/index';
import Beliefs from './components/Beliefs/index';
import Wework from './components/Wework/index';
import Ourteam from './components/Ourteam/index';
import Featured from './components/Featured/index';
import Manage from './components/Manage/index';
import FAQ from './components/FAQ/index';
import Testimonials from './components/Testimonials/index';
import Articles from './components/Articles/index';
import Joinus from './components/Joinus/index';
import Insta from './components/Insta/index';
import Footer from './components/Footer/index';
import Queryformpopup from './components/Queryformpopup/index';
import Video from './components/Video/index'
import Project from './components/Projects/index'
import Brand from './components/Brands/index'

const Home = () => {

   
  return (
    <>
    <div className="overflow-x-hidden">
 
      <Head>
        <title>Grandeur Net</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <Queryformpopup />

        <Navbar />

        <Banner />
        <Digital />
        <div className="flex flex-col items-center w-2/3 mx-auto">
      <div className="relative h-0 overflow-hidden max-w-full w-full rounded-lg" style={{ paddingBottom: '56.25%' }}>
        <iframe
          src="https://www.youtube.com/embed/hv4o7DAwsSs"
          frameBorder="0"
          allowFullScreen
          className="absolute top-0 left-0 w-full h-full shadow-lg"
        ></iframe>
      </div>
    </div>
        <Beliefs />
        <Project/>
        <Brand/>

        {/* <Aboutus /> */}
        {/* <Dedicated /> */}
        {/* <Wework /> */}
        <Ourteam />
        <Featured />
        
        <Manage />
        <FAQ />
        
        <Testimonials />
        
        <Video/>
        {/* <Articles /> */}
        <Joinus />
 
        <Insta />
        
        <Footer />
      </main>
      </div>
    </>
  )
}

export default Home;
